apiVersion: networking.k8s.io/v1 # Kubernetes Ingress API 버전
kind: Ingress # 리소스 종류는 Ingress
metadata:
  name: msa-front-ingress # Ingress 리소스의 이름
  labels:
    app: msa-front # Ingress를 식별하기 위한 라벨
  annotations:
    # AWS ALB Ingress Controller에 특화된 설정 (사용하는 Ingress Controller에 따라 변경 또는 추가)
    kubernetes.io/ingress.class: alb # 사용할 Ingress Controller 지정 (AWS ALB Ingress Controller)
    alb.ingress.kubernetes.io/scheme: internet-facing # 외부 인터넷에서 접근 가능한 로드 밸런서 생성
    alb.ingress.kubernetes.io/target-type: ip # Pod의 IP 주소로 직접 트래픽을 라우팅
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]' # HTTP 포트 리스닝
    alb.ingress.kubernetes.io/subnets: "subnet-04362a3b7f2f40d81,subnet-0009bbca818e1d3bd,subnet-000fdbd8e407a0a5f,subnet-022c5c15b583995b1"
    # alb.ingress.kubernetes.io/ssl-redirect: "true" # HTTP를 HTTPS로 리다이렉트 (HTTPS 설정 시)
    # alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:REGION:ACCOUNT_ID:certificate/CERT_ID # HTTPS를 위한 ACM 인증서 ARN (HTTPS 설정 시)
spec:
  rules:
    # host 필드를 제거하여, ALB의 기본 DNS로 들어오는 요청을 처리합니다.
    - http:
        paths:
          - path: / # 모든 경로에 대한 요청을 라우팅
            pathType: Prefix # '/'로 시작하는 모든 경로 매칭
            backend:
              service:
                name: msa-front # 트래픽을 라우팅할 Service의 이름 (msa-front의 service.yaml 이름과 일치)
                port:
                  number: 80 # Service에서 노출하는 포트 (msa-front의 service.yaml의 port와 일치)
  # tls: # HTTPS를 위한 TLS 설정 (필요시 주석 해제 후 설정)
  #   - hosts: # host 필드가 없으므로, 여기에 도메인을 지정하는 것은 의미가 없을 수 있습니다.
  #       - "" # 빈 문자열을 사용하거나, TLS 설정을 위한 특정 도메인을 필요로 한다면 해당 도메인 지정.
  #     secretName: msa-front-tls-secret # TLS 인증서가 저장된 Kubernetes Secret 이름 (미리 생성해야 함)
