apiVersion: v1
kind: Service
metadata:
  name: msa-front
  namespace: bit-2503
  labels:
    app: msa-front
spec:
  selector:
    app: msa-front
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP